In [23]:
import numpy as np
np.__version__

'1.21.4'

In [24]:
import scipy
scipy.__version__

'1.7.1'

numpy - библиотека для векторизованных вычислений. Написана на Си.
scipy - библиотека для научных вычислений. Написана на Си, С++ и Fortran

### За что не любят Python и любят С/С++?

In [25]:
a = list(range(1_000_000))

In [26]:
%%timeit
[e * e for e in a]

112 ms ± 14.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
a = np.arange(1_000_000)

In [28]:
%%timeit
a * a

1.12 ms ± 28.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Самое медленное место в языке - циклы.

In [29]:
rows, cols = 1_000, 1_000

a = [list(range(i, i + cols)) for i in range(0, rows)]
b = [[0 for j in range(cols)] for i in range(rows)]

In [30]:
%%timeit

for i in range(rows):
    for j in range(cols):
        b[i][j] = 2 * a[i][j]

148 ms ± 18.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
a = np.asarray(a)

In [32]:
%%timeit

2 * a

1.25 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Создание массивов

In [33]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [36]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [38]:
a = np.array([[1, 2, 3, 4, 5], 
             [6, 7, 8, 9, 0]], dtype=float)
a          

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [39]:
a.shape

(2, 5)

In [40]:
a.ndim

2

In [41]:
a.dtype

dtype('float64')

In [42]:
a.astype(int)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

### Размерность массивов

In [44]:
a

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [45]:
a.dtype

dtype('float64')

In [46]:
a.dtype.itemsize

8

In [47]:
a.strides

(40, 8)

In [48]:
b = a.reshape(5, 2)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [49]:
b.shape

(5, 2)

In [50]:
b.strides

(16, 8)

In [51]:
a.reshape(-1, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [53]:
b = a.reshape(5, -1) # same memory

a[0, 1] = -10
b

array([[  1., -10.],
       [  3.,   4.],
       [  5.,   6.],
       [  7.,   8.],
       [  9.,   0.]])

In [54]:
b = a.flatten() # copy
a[0, 1] = -20

b

array([  1., -10.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   0.])

In [55]:
b = a.ravel() # view (same memory)  
a[0, 1] = -30

b

array([  1., -20.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   0.])

In [56]:
c = a.T # view (same memory)  # same as a.transpose()
a[0, 1] = -40

c

array([[  1.,   6.],
       [-40.,   7.],
       [  3.,   8.],
       [  4.,   9.],
       [  5.,   0.]])

In [57]:
c.strides, a.strides

((8, 40), (40, 8))

### Фиктивная ось - ось с размерностью 1.

In [58]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b[np.newaxis, :] # same as b.reshape(1, *b.shape)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
np.expand_dims(b, axis=0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
b[:, np.newaxis] # same as b.reshape(*b.shape, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [63]:
b[np.newaxis, :, np.newaxis].shape

(1, 10, 1)

### Создание массивов с особыми свойствами